version: "3.8"

services:
  db:
    container_name: plusmedical-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: plusmedical
      POSTGRES_PASSWORD: plusmedical
      POSTGRES_DB: plusmedical
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ui:
    container_name: plusmedical-ui
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/plusmedical
    depends_on:
      - db
    networks:
      - net
    env_file:
      - .env

networks:
  net:
    driver: bridge

volumes:
  postgres_data: {}
