version: "3.8"
services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ${APP_NETWORK}
    volumes:
      - postgres_data:${POSTGRES_VOLUME}

  ui:
    container_name: ${UI_HOST}
    image: ${DOCKER_USERNAME}/${UI_HOST}
    build:
      context: .
      dockerfile: frontend.dockerfile
    depends_on:
      - db
    networks:
      - ${APP_NETWORK}

networks:
  net:
    driver: bridge

volumes:
  postgres_data: {}
